# Slack Verification Tokens

slack_secret: ''

slack_oauthtoken: ''

verification_token: ''

# OpenAI Verification Tokens

openai_token: ""

# Vectorstore Location

vectorstore: "./vectorstore/"

# Data Processing Stuff
# https://www.jcrew.com/sitemap-wex/sitemap-pdp1.xml

web_sites: ["https://www.jcrew.com/sitemap-wex/sitemap-pdp1.xml",
]



